[package]
name = "router-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
env_logger  = { workspace = true }
redis       = { workspace = true }
tokio       = { workspace = true }
log         = { workspace = true }
mini-config = { workspace = true }
crossterm   = { workspace = true }
pingora     = { git = "https://github.com/zonblade/pingora.git", branch = "zonblade/sfv-temporal-fix", features = ["proxy", "lb", "cache", "openssl"] }
ctrlc = "3.4.5"
regex = "1.11.1"
http = "1.3.1"
