[workspace]
resolver = "2"
members = [
    "router-api",
    "router-cli",
    "router-core",
    "router-gui"
]

[workspace.dependencies]
async-trait = "0.1.88"
env_logger  = "0.11.7"
tracing     = "0.1.41"
log         = "0.4"
mini-config = { version = "0.1.3" , features = [ "derive" ] }
crossterm   = { version = "0.28.1", features = [ "event-stream" ] }
redis       = { version = "0.29.2", features = [ "tokio-comp" ] }
tokio       = { version = "1.44.1", features = [ "full" ] }