[package]
name = "router-gui"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web   = { workspace = true }
actix-cors  = { workspace = true }
serde_json  = { workspace = true }
serde       = { workspace = true , features = [ "derive" ] }
include_dir = "0.7.3"