[package]
name = "router-gui"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web   = { workspace = true }
actix-cors  = { workspace = true }
mini-config = { workspace = true }
serde_json  = { workspace = true }
serde       = { workspace = true , features = [ "derive"         ] }