[package]
name = "router-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
mini-config     = { workspace = true }
crossterm       = { workspace = true }
clap            = { version = "4.5.35", features = ["derive"] }
reqwest         = { version = "0.12", features = ["json", "stream"] }
serde           = { version = "1.0.219", features = ["derive"] }
tokio           = { workspace = true }
serde_json      = { workspace = true }
serde_yaml      = "0.9.29"
thiserror       = "1.0.56"
chrono          = { version = "0.4", features = ["serde"] }
log             = "0.4.20"
env_logger      = "0.11.1"
dirs            = "5.0.1"
ratatui         = "0.29"
futures-util    = "0.3"