name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

# ignore jobs for now.

jobs:
  build:

    runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Cargo Check
#       run: cargo check --verbose
